### ISSUE TITLE
provenance and cosmwasm v2.1.0

### ISSUE THREAD

**Issue by PFC-developer** [strangelove-ventures/heighliner#258]
for the following chain data
```
# Provenance
- name: provenance
  github-organization: provenance-io
  github-repo: provenance
  dockerfile: cosmos
  build-target: make install
  binaries:
    - /go/bin/provenanced
  build-env:
    - WITH_LEDGER=false
    - WITH_CLEVELDB=false
    - BUILD_TAGS=muslc musl dynamic
```
and building via
```
./heighliner build --no-cache --no-build-cache --chain provenance --git-ref v1.19.0
```
it's go.mod contains

`github.com/CosmWasm/wasmvm/v2 v2.1.0
`
which should generate a wget to 
`
https://github.com/CosmWasm/wasmvm/releases/download/v2.1.0/libwasmvm_muslc.x86_64.a
`
but instead generates 
`
https://github.com/CosmWasm/wasmvm/v2/releases/download/v2.1.0/libwasmvm_muslc.x86_64.a
`

I'm not raising a PR here, as I don't think this is the correct thing to do (but it appears to work)

```
diff --git a/builder/builder.go b/builder/builder.go
index c6b66e9..e7aebaa 100644
--- a/builder/builder.go
+++ b/builder/builder.go
@@ -255,6 +255,10 @@ func getWasmvmVersion(modFile *modfile.File) string {
                        wasmvmVersion = item.Syntax.Token[len(item.Syntax.Token)-1]
                }
        }
+       if (wasmvmVersion == "v2.1.0") {
+               fmt.Printf("WasmVM from go.mod: 2.1 hack applied\n")
+               wasmvmRepo = defaultWasmvmRepo
+       }

        fmt.Printf("WasmVM from go.mod: repo: %s, version: %s\n", wasmvmRepo, wasmvmVersion)
```
allows it to pass the download stage
