### ISSUE TITLE
Heighliner should include Bandchain in its list of packages.

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/heighliner#31]
`chains.yaml`:

```yaml
# Bandchain
- name: bandchain
  github-organization: bandprotocol
  github-repo: chain
  language: go
  build-target: install
  binaries:
    - /go/bin/bandd
  build-env:
    - BUILD_TAGS=muslc
 ```

Error: 

```
...
# github.com/bandprotocol/chain/v2/cmd/bandd
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: warning: librt.so.1, needed by /go/pkg/mod/github.com/bandprotocol/go-owasm@v0.1.0/api/libgo_owasm.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libpthread.so.0, needed by /go/pkg/mod/github.com/bandprotocol/go-owasm@v0.1.0/api/libgo_owasm.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libm.so.6, needed by /go/pkg/mod/github.com/bandprotocol/go-owasm@v0.1.0/api/libgo_owasm.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libdl.so.2, needed by /go/pkg/mod/github.com/bandprotocol/go-owasm@v0.1.0/api/libgo_owasm.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libc.so.6, needed by /go/pkg/mod/github.com/bandprotocol/go-owasm@v0.1.0/api/libgo_owasm.so, not found (try using -rpath or -rpath-link)
...
```

**Comment by boojamya** [comment]
Seeing same issue as bandchain. See:

https://github.com/strangelove-ventures/heighliner/issues/39#issuecomment-1248566988

**Comment by MarcelMWS** [comment]
Hi, here is a workaround:

`chains.yaml`:

```
# Bandchain
- name: bandchain
  github-organization: bandprotocol
  github-repo: chain
  language: go
  build-target: install
  binaries:
    - /go/bin/bandd
  libraries:
    - /go/pkg/mod/github.com/bandprotocol/go-owasm@v0.2.2/api/libgo_owasm.so
```

and apply this patch to `dockerfile/sdk/native.Dockerfile`

```patch
diff --git a/dockerfile/sdk/native.Dockerfile b/dockerfile/sdk/native.Dockerfile
index 3b46933..ca6642e 100644
--- a/dockerfile/sdk/native.Dockerfile
+++ b/dockerfile/sdk/native.Dockerfile
@@ -1,6 +1,6 @@
-FROM golang:1.19-alpine3.16 AS build-env
+FROM golang:1.19-bullseye AS build-env

-RUN apk add --update --no-cache curl make git libc-dev bash gcc linux-headers eudev-dev ncurses-dev
+RUN apt-get install curl make git libc-dev bash gcc

 ARG TARGETARCH
 ARG BUILDARCH
@@ -73,8 +73,8 @@ RUN addgroup --gid 1025 -S heighliner && adduser --uid 1025 -S heighliner -G hei
 # Use ln and rm from full featured busybox for assembling final image
 FROM busybox:1.34.1-musl AS busybox-full

-# Build final image from scratch
-FROM scratch
+# Build final image
+FROM golang:1.19-buster

 LABEL org.opencontainers.image.source="https://github.com/strangelove-ventures/heighliner"

@@ -86,20 +86,6 @@ COPY --from=busybox-full /bin/ln /bin/rm ./
 # Install minimal busybox image as shell binary (will create hardlinks for the rest of the binaries to this data)
 COPY --from=busybox-min /busybox/busybox /bin/sh

-# Add hard links for read-only utils, then remove ln and rm
-# Will then only have one copy of the busybox minimal binary file with all utils pointing to the same underlying inode
-RUN ln sh pwd && \
-    ln sh ls && \
-    ln sh cat && \
-    ln sh less && \
-    ln sh grep && \
-    ln sh sleep && \
-    ln sh env && \
-    ln sh tar && \
-    ln sh tee && \
-    ln sh du && \
-    rm ln rm
-
 # Install chain binaries
 COPY --from=build-env /root/bin /bin
```

Tested with:

`./heighliner build -c bandchain -v v2.4.1`

Info:

There are some issues with alpine build and final images sometimes. Just switch to debian bullseye 🎯 image. You have to take a closer look at what problems alpine is causing. Hopefully I could help
