### ISSUE TITLE
Build github actions workflow

### ISSUE THREAD

**Issue by agouin** [strangelove-ventures/heighliner#75]
Build github actions workflow so that heighliner images can be built and push from an importable workflow.

### With built-in chain config
```yaml
      - name: Build and push heighliner Docker image
        uses: heighliner/build-push-action@v1
        with:
          chain: gaia
```

### Custom chain config

```yaml
      - name: Build and push heighliner Docker image
        uses: heighliner/build-push-action@v1
        with:
          chain: somechain
          language: go
          build-target: install
          build-env:
            - LEDGER_ENABLED=false
            - BUILD_TAGS=muslc
          binaries:
            - /go/bin/somechaind
```
